### ISSUE TITLE
[Bug] Loading stops halfway

### ISSUE THREAD

**Issue by Monniasza** [KSPSnark/BetterBurnTime#14] opened 2020-04-25 17:30 UTC
[KSP.log](https://github.com/KSPSnark/BetterBurnTime/files/4533590/KSP.log)

KSP Version: 1.8.1.2694
Mod Version: 1.10

The mod causes game to stop loading halfway due to config loading error.

**Comment by SmallerDragons** [comment] 2021-08-07 22:23
Am also receiving this issue, currently have to remove the mod from all mod packs to prevent asset loading holdups. Doesn't seem to have any conflict with any other mods in my testing

**Comment by OortCloud42** [comment] 2021-08-07 22:55
Also receiving this issue.

**Comment by KSPSnark** [comment] 2021-08-10 21:53
I'm unable to reproduce this on KSP 1.12.2.  Starts up just fine for me.

It's clear that _some_ people are getting it, so thank you for the report, but if I can't reproduce it myself then there's not really anything I can do, here.  Does someone have a reliable repro case?  Have you tried running BBT on KSP 1.12.2 on an otherwise clean KSP install that doesn't have any other mods present, and still get the hang?

* If you can reproduce it in some older KSP version, *but not in KSP 1.12.2* (which is current as of this writing), then that's not something I'm going to spend time on to debug; I don't have time to support anything other than the version of KSP that I play, which is always the most recent.  (But if someone _else_ did the work to dive into the code and find out what's causing the problem, and had a fix in hand that I could test out in KSP 1.12.2, I'd be willing to consider it.)
* If you can't reproduce it on a clean KSP with only BBT running, but you _do_ get it with some other mods installed... then it's a mod compatibility problem and the thing to do would be to narrow down which other mod is causing the issue.

If someone is able to come up with a clean repro case in current KSP, which I can reproduce, then I'd be happy to have a look at this-- feel free to open an issue with repro steps.  Otherwise, this is "won't fix".

**Closed as completed by KSPSnark** 2021-08-10 21:53 UTC
